pkg/base/common.go
pkg/base/operator.go

Because
- we need an interface for operators similar to connectors
This commit
- adds an interface for operators
TODO NEXT:
1. Protobuf changes for operator
2. Move common code to component and only specifics in operator and connector interface

chore: define operator interface

---

.github/CONTRIBUTING.md

Because
- we need more content in contributing guidelines
This commit
- update contributing guidelines

docs(contributing): update contributing guidelines

---

go.mod
pkg/base/component.go
pkg/jsonref/interface.go
pkg/jsonref/options.go
pkg/jsonref/ref.go

Because
- the json reference didn't preserve additional attributes 
This commit
- update json reference to include additional attributes

chore(component): update json reference to include additional attributes

---

pkg/base/connector.go

Because
- we should always have `instillShortDescription` value even if the implementation doesn't have this.
This commit
- use `description` as fallback value of `instillShortDescription`

chore(connector): use `description` as fallback value of `instillShortDescription`

---

pkg/base/component.go
pkg/base/connector.go

Because
- there is a `instillShortDescription` bug
This commit
- fix refineResourceSpec func bug

chore(connector): fix refineResourceSpec func bug

---

pkg/base/component.go

Because
- we need to describe the condition field in json-schema
This commit
- add json-schema field for condition setting

chore(component): add json-schema field for condition setting

---

pkg/base/component.go

Because
- In our current implementation, the `instillFormat: semi-structured/object` only allows for `object` data. However, in some scenarios, we would like to define a field as JSON. JSON data can be an object, array, number, string, or boolean.
This commit
- Introduce `instillFormat: semi-structured/json`; this instillFormat will be treated as a free-form data type, which means we won't have a `type` in the JSON schema.

feat: introduce `instillFormat: semi-structured/json`

---

pkg/connector/instill/v0/main.go

Because
- The Instill Model connector can't work properly in internal mode since the pods in different region clusters can't connect to each other, we decided to use external IP and bypass the user authorization.
This commit
- Fixes the multi-region connection problem by bypassing the user authorization header.

fix(instill): fix multi-region connection problem

---

.github/workflows/test-compogen.yml
tools/compogen/cmd/testdata/readme-connector.txt
tools/compogen/pkg/gen/definition_test.go
tools/compogen/pkg/gen/resources/templates/readme.mdx.tmpl
tools/compogen/pkg/gen/schema.go
tools/compogen/pkg/gen/schema_test.go

Because
- `compogen` tests are broken
This commit
- fixes tests
- adds action to check `compogen` when changed

feat: test compogen on PR and push events

---

pkg/connector/instill/v0/main.go

Because
- We want to cache the model list in memory when `__STATIC_MODEL_LIST` is true.
This commit
- Caches the definition if the variable `__STATIC_MODEL_LIST` is true.

chore(instill): cache definition if var `__STATIC_MODEL_LIST` is true

---

.github/CONTRIBUTING.md

Because
- We need a guide to onboard newcomers and external contributors to add new components.
This commit
- Fixes outdated documentation in the contribution guidelines.
- Adds a section with the steps to add a `hello, world!` component.

feat: add contribution guide

---

pkg/connector/slack/v0/apiFunctions.go

Because
- channelID is wrong to set
This commit
- fix set channelID bug

fix: Fix the bug of setting channelID

---

pkg/connector/slack/v0/config/definition.json
pkg/connector/slack/v0/taskFunctions.go

Because
- We want the token is secret.
This commit
- make the token secret

fix(slack): add `instillSecret: true` to `token` field

---

go.mod
go.sum
pkg/connector/instill/v0/client.go
pkg/connector/instill/v0/image_classification.go
pkg/connector/instill/v0/image_to_image.go
pkg/connector/instill/v0/instance_segmentation.go
pkg/connector/instill/v0/keypoint_detection.go
pkg/connector/instill/v0/main.go
pkg/connector/instill/v0/object_detection.go
pkg/connector/instill/v0/ocr.go
pkg/connector/instill/v0/semantic_segmentation.go
pkg/connector/instill/v0/text_generation.go
pkg/connector/instill/v0/text_generation_chat.go
pkg/connector/instill/v0/text_to_image.go
pkg/connector/instill/v0/visual_question_answering.go

Because
- We are going to introduce the new Instill Model services and which endpoints are not compatible with old ones.
This commit
- Adopts latest Model endpoints.

feat(instill): adopt latest Model endpoints

---

ai/instill/v0/main.go

Because
- The `GetDefinition()` in Instill Model connector doesn't work correctly.
This commit
- Fixes and optimizes `GetDefinition()`

chore(instill): fix and optimize `GetDefinition()`

---

ai/archetypeai/v0/README.mdx
ai/archetypeai/v0/config/setup.json
ai/huggingface/v0/README.mdx
ai/huggingface/v0/config/setup.json
ai/openai/v0/README.mdx
ai/openai/v0/config/setup.json
ai/stabilityai/v0/README.mdx
ai/stabilityai/v0/config/setup.json
application/numbers/v0/README.mdx
application/numbers/v0/config/setup.json
base/testdata/connectorConfig.json
base/testdata/wantConnectorDefinition.json
data/pinecone/v0/README.mdx
data/pinecone/v0/config/setup.json
data/redis/v0/client.go
data/redis/v0/main.go
tools/compogen/cmd/testdata/readme-connector.txt

Because
- spot some typos and format inconsistent 
This commit
- fix typos and format

fix(all): fix typos

---

.github/CONTRIBUTING.md

Because
- the `CONTRIBUTION.md` file has typos and inconsistent content with the latest documentation website
This commit
- update the file

docs(CONTRIBUTION): align content with the latest documentation

---

application/email/v0/.compogen/extra-setup.mdx
application/email/v0/README.mdx

Because
- the name of providers should be correct
This commit
- update doc to correct providers' name

chore: update doc

---

ai/anthropic/v0/README.mdx
ai/anthropic/v0/component_test.go
ai/anthropic/v0/config/setup.json
ai/anthropic/v0/config/tasks.json
ai/anthropic/v0/main.go
store/store.go

Because
- We need to calculate the usage of the Anthropic component.
This commit
- Adds usage tokens to component output.
- Adds usage handler related functions.

feat(anthropic): add UsageHandler functions in anthropic

---

ai/openai/v0/config/openai.json

Because
- We want to group the GPT-4 model family together.
This commit
- Updates the model list order

chore(openai): update model list order

---

ai/instill/v0/client.go
ai/instill/v0/image_classification.go
ai/instill/v0/image_to_image.go
ai/instill/v0/instance_segmentation.go
ai/instill/v0/keypoint_detection.go
ai/instill/v0/main.go
ai/instill/v0/object_detection.go
ai/instill/v0/ocr.go
ai/instill/v0/semantic_segmentation.go
ai/instill/v0/text_generation.go
ai/instill/v0/text_generation_chat.go
ai/instill/v0/text_to_image.go
ai/instill/v0/unspecified.go
ai/instill/v0/visual_question_answering.go

Because
- The model-backend provides new namespace endpoints
This commit
- Adopts the latest model endpoints

chore(instill): adopt latest model endpoint

---

ai/groq/v0/README.mdx
data/artifact/v0/.compogen/extra-intro.mdx
data/artifact/v0/README.mdx

Because
- OPENAI_API_KEY is only for instill core
This commit
- update the document

chore(artifact, groq): update document

---

data/artifact/v0/README.mdx
data/artifact/v0/config/definition.json
data/artifact/v0/config/tasks.json
data/artifact/v0/main.go

Because
- the name is confusing users
This commit
- change the name

chore(artifact): update task name

---

operator/document/v0/README.mdx
operator/document/v0/config/tasks.json
operator/document/v0/convert.go
operator/document/v0/convert_test.go
operator/document/v0/main_test.go

Because
- we want to make doc clear and vdp consistent
This commit
- update the doc and field in document operator

chore(document): update doc and key to make vdp consistent

---

application/hubspot/v0/get_all_test.go
application/hubspot/v0/owner_test.go

Because
- we change the interface, which makes test code failed
This commit
- fix test code

fix(hubspot): fix test code

---

data/milvus/v0/README.mdx
data/milvus/v0/config/tasks.json

Because
- doc looks messy in UI
This commit
- use anchor text links to tidy up document

chore(milvus): use anchor text links to tidy up document

---

application/hubspot/v0/README.mdx
application/hubspot/v0/config/setup.json
application/hubspot/v0/config/tasks.json
data/milvus/v0/README.mdx
data/milvus/v0/config/tasks.json
data/zilliz/v0/README.mdx
data/zilliz/v0/config/tasks.json

Because
- doc UI looks messy
This commit
- update doc with anchor text for link

chore(zilliz,hubspot): update doc

---

data/chroma/v0/component_test.go
data/chroma/v0/main.go

Because
- we change interface of component
This commit
- change interface of chroma

fix(chroma): change interface

---

operator/document/v0/python/transformPDFToMarkdown.py

Because
- there are some potential improvement in pdf to markdown
This commit
- add indent
- tune height param for h1 and h2

feat(document): improve pdf to markdown

---

operator/document/v0/python/transformPDFToMarkdown.py

Because
- pdfplumber extract text with lots of attributes, which increase memory insanely
This commit
- reset the memory by 30 pages extracting to avoid memory increasing too much

fix(document): fix memory increasing problem

---

operator/text/v0/markdown_splitter.go

Because
- there is infinity loop
This commit
- set the protection and fix the bugs

fix(text): bug of infinity loop

---

operator/document/v0/python/transformPDFToMarkdown.py

Because
- pdfplumber does not clear the page cache itself
This commit
- clear page cache

fix(text): fix memory problem

---

ai/openai/v0/config/tasks.json
ai/openai/v0/main.go
ai/openai/v0/text_generation.go

Because
- OpenAI has released the new models.
This commit
- Adds support for o1-series models.

feat(openai): add support for o1-series models

---

operator/text/v0/markdown_document.go

Because
- there is a bug if there is a document without content
This commit
- fix bug

fix(text): fix bugs for short file

---

store/store.go

Because
- we want to release universal ai and instill app component
This commit
- init them in component store

chore: init components to be released

---

ai/anthropic/v0/README.mdx
ai/cohere/v0/README.mdx
ai/fireworksai/v0/README.mdx
ai/groq/v0/README.mdx
ai/instill/v0/README.mdx
ai/mistralai/v0/README.mdx
ai/ollama/v0/README.mdx
ai/openai/v0/README.mdx
tools/compogen/pkg/gen/readme.go

Because
- the json format is wrong in mdx
This commit
- fix json format

fix(compogen): fix json format

---

ai/anthropic/v0/README.mdx
ai/cohere/v0/README.mdx
ai/fireworksai/v0/README.mdx
ai/groq/v0/README.mdx
ai/instill/v0/README.mdx
ai/mistralai/v0/README.mdx
ai/ollama/v0/README.mdx
ai/ollama/v0/config/tasks.json
ai/openai/v0/README.mdx
application/whatsapp/v0/README.mdx
application/whatsapp/v0/config/setup.json
application/whatsapp/v0/config/tasks.json
data/bigquery/v0/README.mdx
data/chroma/v0/README.mdx
data/elasticsearch/v0/README.mdx
data/elasticsearch/v0/config/tasks.json
data/instillartifact/v0/.compogen/extra-intro.mdx
data/instillartifact/v0/README.mdx
data/instillartifact/v0/config/tasks.json
data/milvus/v0/README.mdx
data/mongodb/v0/README.mdx
data/mongodb/v0/config/tasks.json
data/qdrant/v0/README.mdx
data/qdrant/v0/config/tasks.json
data/redis/v0/README.mdx
data/sql/v0/README.mdx
data/weaviate/v0/README.mdx
data/weaviate/v0/config/tasks.json
data/zilliz/v0/README.mdx
tools/compogen/pkg/gen/readme.go

Because
- there are some typos in the current doc
This commit
- fix typo
- use anchor text for URL

chore: update docs
