instill-ai/component

- pkg/objectmapper/mapper.go
Because
- we need this function as exported to use in operator repo
This commit
- makes the function `getSrcValueByTag` as exported
> chore: make GetSrcValueByTag as exported func

- .github/CONTRIBUTING.md
Because
- current contribution guidelines don't have any sample PRs
This commit
- adds a few sample PRs for reference
> chore: add sample PRs to contribution guidlines

- pkg/base/component.go
Because
- we want to make the component configuration has consistent structure
This commit
- make every component has `task`
> chore(component): make every component has `task`

- pkg/base/component.go
- pkg/base/connector.go
- pkg/base/operator.go
Because
- we need to mark which fields allow using template
This commit
- support `instillUpstreamType`: `template`
- support `instillUpstreamType` for `patternProperties`
> chore(jsonschema): support `instillUpstreamType`: `template`

- pkg/base/connector.go
Because
- we want all self-defined json-schema annotation has `instill` prefix
This commit
- rename `credential_field` to `instillCredentialField`
> chore(connector): rename credential_field to instillCredentialField

- pkg/base/component.go
Because
- there is a bug in OpenAPI json-schema traverser
This commit
- fix OpenAPI json-schema array bug
> chore(connector): fix OpenAPI json-schema array bug

- .github/workflows/coverage.yml
Because
- we need to update github action default token
This commit
- update github action default token
> ci(workflow): update github action default token

- shared_schema.json
Because
- we should use `instillFormat: array` to simplify the json-schema structure
This commit
- refactor `instillFormat: xxx_array` to `array`
> refactor(component): refactor instillFormat xxx_array to array

- schema.json
Because
- `boundingBox` has been renamed to `bounding_box` to be consistent with gRPC naming convention
This commit
- fix the inconsistency
- rename file `shared_schema.json` to `schema.json`
- close instill-ai/community#470
> fix(schema): fix schema inconsistent naming

- .pre-commit-config.yaml
- release-please/config.json
- schema.json
Because
- we need pre-commit hook to format and standardize the json file automatically
This commit
- update pre-commit hook for json formatting
> ci(precommit): update pre-commit hook for json formatting

- pkg/base/component.go
- schema.json
Because
- we introduced a new field `instillAcceptFormats` for smart-hint feature.
This commit
- refactor `instillAcceptFormats`
> refactor(component): refactor instillAcceptFormats

- pkg/base/component.go
Because
- we should parse `instillAcceptFormats` rather than `instillFormat` in `convertDataSpecToCompSpec()`
This commit
- fix bug
> chore(component): fix `instillAcceptFormats` in `convertDataSpecToCompSpec()`

- pkg/base/component.go
Because
- the `instillShortDescription` wasn't correctly parsed
This commit
- fix `instillShortDescription` parser bug
> fix(component): fix `instillShortDescription` parser bug

- pkg/jsonref/ref.go
Because
- the jsonreference has a pointer bug, causing the content error
This commit
- fix jsonreference pointer bug
> fix(component): fix jsonreference pointer bug

- go.mod
- go.sum
- pkg/base/execution.go
- pkg/base/formats.go
Because
- besides the original json-schema, we also need to validate the `instillAcceptFormats` and `instillFormat` for component input and output
This commit
- add json-schema validator for `instillAcceptFormats` and `instillFormat`
> refactor(component): add json-schema validator for `instillAcceptFormats` and `instillFormat`

- pkg/base/formats.go
Because
- Some base64 string will contain data mime type prefix, we should trim them.
This commit
- Add `TrimBase64Mime` func
> chore(component): add `TrimBase64Mime` func

- pkg/base/formats.go
Because
- we need a function to convert `array:<format>` format
This commit
- add `CompileInstillFormat` helper function
> chore(component): add `CompileInstillFormat` helper function

- pkg/base/component.go
Because
- the `type` is missing in component OpenAPI schema
This commit
- fix OpenAPI schema bug
> chore(component): fix OpenAPI schema bug

- pkg/base/formats.go
Because
- we'd like to add MIME prefix for all base64 data
This commit
- refactor Validate() to support base64 with MIME prefix
> chore(component): refactor Validate() to support base64 with MIME prefix

- schema.json
Because
- we need to mark instillFormat in the array item as well
This commit
- refactor instillFormat `structured/*`
> refactor(schema): refactor instillFormat `structured/*`

- schema.json
Because
- We need to standardize the chat history format across all LLM tasks.
This commit
- add `structured/multi_modal_content` instillFormat
- add `structured/chat_messages` instillFormat
> feat(schema): add new instillFormat for chat history

- pkg/base/connector.go
Because
- The connector `credentialFields` does not work inside the `oneOf` JSON schema.
This commit
- Fixes the `credentialFields` bug inside the `oneOf` JSON schema.
> fix(connector): fix credentialFields bug inside `oneOf` schema

- pkg/base/component.go
Because
- We need to make the smart hint works for `condition` field on Console, so we need to update the `instillUpstreamTypes`.
This commit
- add `instillUpstreamTypes: template` in component condition field
> feat: add `instillUpstreamTypes: template` in component condition field

- pkg/base/connector.go
- pkg/base/operator.go
Because
Originally, our connector definitions are fixed. However, in some scenarios, the definition will be dynamic.
The component JSON schema can be influenced by connector configuration. For example, the Instill Model Connector can retrieve the model list and incorporate it into the component JSON schema as an enumeration.
The OpenAPI schema can be influenced by both connector and component configuration. For example, we can let user define the JSON schema of the output body in the RestAPI connector and utilize it to generate the OpenAPI schema of the RestAPI connector.
Therefore, we would like to make these connector definitions dynamically generated.
This commit
- update GetOperatorDefinition functions to support dynamic definition
> feat: update GetOperatorDefinition functions to support dynamic definition

- go.mod
- pkg/base/component.go
Because
- we want to display human-readable titles and descriptions for tasks
This commit
- add the task title and description to the component's JSON schema.
> feat: add task title and description in component json schema

- schema.json
Because
- We want to use `title` to generate class-name in Python-SDK
This commit
- Update `title` in JSON schema
> chore: update title in JSON schema

- pkg/base/formats.go
Because
- When `instillAcceptFormats` have more than one value, the component data validation will go wrong.
This commit
- Fixes bug when `instillAcceptFormats` has multiple values.
> fix: fix bug when `instillAcceptFormats` has multiple values

- pkg/base/formats.go
Because
- The `instillFormat` validation has a bug when dealing with `semi-structured` and `structured` data. In such cases, base64 encoding should not be checked.
This commit
- Skips `instillFormat` base64 validation when `instillFormat` is classified as `semi-structured` or `structured`.
Note
- The current approach is somewhat hard-coded. We should optimize the flow in the future.
> fix: fix `instillFormat` validation when using `semi-structured` and `structured data`

- pkg/base/component.go
Because
- INS-3584 (README auto-gen) needs to build the task title in case it isn't
defined in the task schema.
This commit
- Extracts the already implemented code for task titles to a public method.
> feat: extract task title generation

- go.mod
- go.sum
- pkg/base/connector.go
- pkg/base/operator.go
- tools/compogen/README.md
- tools/compogen/go.mod
- tools/compogen/go.sum
- tools/compogen/pkg/gen/resources/templates/readme.mdx.tmpl
Because
- Component page includes a short description of the component.
- `operator` and `connector` descriptions were added / updated to use the imperative tense
This commit
- Includes the latest version of `protogen-go`, which exposes the `description` field. This will be automatically loaded from `definitions.json`
- Adds a minor optimization that sets the capacity component list slices, avoiding potential reallocations as the list grows.
- Updates the `compogen readme` template to use the descriptions in imperative tense.
> feat: expose description field in component entities

- pkg/base/component.go
- pkg/base/connector.go
- pkg/base/operator.go
- tools/compogen/cmd/testdata/readme-connector.txt
- tools/compogen/cmd/testdata/readme-operator.txt
Because
- `description` field in operator is now in imperative format
- When a connector / operator definition is fetched, it is pulled from the component definition list. When an error occurs, we can't know if it's because it doesn't exist or because the type is wrong.
This commit
- Updates `compogen` tests
- Improves the error messages for the "get by ID / UID" component definition methods.
> fix(vdp): better casting errors

- tools/compogen/README.md
- tools/compogen/cmd/testdata/readme-connector.txt
- tools/compogen/cmd/testdata/readme-operator.txt
- tools/compogen/go.mod
- tools/compogen/go.sum
- tools/compogen/pkg/gen/definition.go
- tools/compogen/pkg/gen/definition_test.go
- tools/compogen/pkg/gen/readme.go
- tools/compogen/pkg/gen/readme_test.go
- tools/compogen/pkg/gen/resources/templates/readme.mdx.tmpl
Because
- A `release_stage` field was [introduced](https://github.com/instill-ai/connector/pull/138) in `definitions.json`
This commit
- Uses the field to render the release stage instead of extracting it from `version` (which doesn't contain stages like GA, coming soon or open for contributions).
> feat: read release stage in auto generated docs from field in definitions

- .github/CONTRIBUTING.md
Because
- The `definitions.json` structure relies on dev knowledge.
- CONTRIBUTING guidelines have outdated info
This commit
- Corrects outdated info
- Adds a section about how to bump the version of a component and how to keep it aligned with the release version.
> feat: document release stages and versions

- .github/CONTRIBUTING.md
Because
- `release_stage` refers to the component and the pre-release label in the version informs about the state of a given version, so it's better to use only major-minor-patch versions in components.
This commit
- Updates the contributing guidelines with the decision.
> fix: document pre-release version removal

- tools/compogen/README.md
Because
- Installing the tool doesn't require `git`, only `go`
This commit
- Updates `compogen`'s README to simplify the installation command
> fix(compogen): better installation command

- .github/CONTRIBUTING.md
- go.mod
- go.sum
- pkg/base/connector.go
- pkg/connector/airbyte/v0/main.go
- pkg/connector/archetypeai/v0/connector_test.go
- pkg/connector/archetypeai/v0/main.go
- pkg/connector/bigquery/v0/main.go
- pkg/connector/googlecloudstorage/v0/main.go
- pkg/connector/googlesearch/v0/main.go
- pkg/connector/huggingface/v0/main.go
- pkg/connector/instill/v0/main.go
- pkg/connector/main.go
- pkg/connector/numbers/v0/main.go
- pkg/connector/openai/v0/connector_test.go
- pkg/connector/openai/v0/main.go
- pkg/connector/pinecone/v0/main.go
- pkg/connector/redis/v0/main.go
- pkg/connector/restapi/v0/connector_test.go
- pkg/connector/restapi/v0/main.go
- pkg/connector/stabilityai/v0/connector_test.go
- pkg/connector/stabilityai/v0/main.go
- pkg/connector/website/v0/main.go
Because
- We can simplify the `Test()` function in the connector to use only the error message instead of an additional enum.
This commit
- Adjusts `Test()` interface and removes the state enum.
- Adopts latest protogengo.
> feat: adjust `Test()` interface

- go.mod
- go.sum
- pkg/base/connector.go
- pkg/connector/airbyte/v0/main.go
- pkg/connector/instill/v0/main.go
- pkg/connector/integration_test.go
- pkg/connector/main.go
- pkg/connector/restapi/v0/main.go
Because
- Originally, we had a `resourceConfig` parameter in the `GetConnectorDefinitionByID()` and `GetConnectorDefinitionByUID()` functions. Since we retired the connector resource, these two parameters are not needed.
This commit
- Removes the `resourceConfig` parameter.
> feat: adjust `IConnector` interface

- pkg/connector/airbyte/v0/config/definition.json
- pkg/connector/airbyte/v0/config/seed/generate_definitions.py
Because
- The release_stage of `Airbyte` connector was missing.
This commit
- Adds missing `release_stage`.
> fix(airbyte): add missing release_stage

- pkg/connector/airbyte/v0/config/definition.json
- pkg/connector/airbyte/v0/config/seed/generate_definitions.py
Because
- the Airbyte connector has some schema that are not supported in Console auto-form.
This commit
- refines definition.
- removes local connectors for security purpose.
> feat(airbyte): remove local connector and refine definition

- pkg/base/connector.go
- pkg/base/testdata/wantConnectorDefinition.json
Because
- We've retired the connector resource, there is no need to have two specifications for resource and component. We can merge them into one.
This commit:
- Merges the resource spec into the component spec.
Note:
- We keep the old resource spec for now. It will be removed soon.
> feat: merge resource spec into component spec

- pkg/base/connector.go
- pkg/connector/main.go
Because
- We need to provide interface for pipeline-backend to check credential fields.
This commit
- Exposes `IsCredentialField` interface.
> feat: expose `IsCredentialField` interface

- pkg/connector/archetypeai/v0/config/definition.json
- pkg/connector/bigquery/v0/config/definition.json
- pkg/connector/googlecloudstorage/v0/config/definition.json
- pkg/connector/googlesearch/v0/config/tasks.json
- pkg/connector/huggingface/v0/config/definition.json
- pkg/connector/instill/v0/config/definition.json
- pkg/connector/numbers/v0/config/definition.json
- pkg/connector/openai/v0/config/definition.json
- pkg/connector/pinecone/v0/config/definition.json
- pkg/connector/redis/v0/config/definition.json
- pkg/connector/restapi/v0/config/definition.json
- pkg/connector/stabilityai/v0/config/definition.json
Because
- We need to include `instillAcceptFormats` in the JSON schema for the Console's auto-form to function correctly.
This commit
- Adds instillAcceptFormats in connection JSON schema.
> chore: add instillAcceptFormats in connection JSON schema

- pkg/connector/archetypeai/v0/config/definition.json
- pkg/connector/bigquery/v0/config/definition.json
- pkg/connector/googlecloudstorage/v0/config/definition.json
- pkg/connector/googlesearch/v0/config/definition.json
- pkg/connector/huggingface/v0/config/definition.json
- pkg/connector/instill/v0/config/definition.json
- pkg/connector/numbers/v0/config/definition.json
- pkg/connector/openai/v0/config/definition.json
- pkg/connector/pinecone/v0/config/definition.json
- pkg/connector/redis/v0/config/definition.json
- pkg/connector/restapi/v0/config/definition.json
- pkg/connector/stabilityai/v0/config/definition.json
Because
- We need to include `instillUpstreamTypes` in the JSON schema for the Console's auto-form to function correctly.
This commit
- Adds `instillUpstreamTypes` in connection JSON schema.
> chore: add instillUpstreamTypes in connection JSON schema

- pkg/connector/main.go
- pkg/operator/main.go
Because
- The `ListOperatorDefinitions` and `ListConnectorDefinitions` data should was not ordered.
This commit
- Fix the bug.
> chore: the ListOperatorDefinitions and ListConnectorDefinitions should be ordered

- pkg/connector/openai/v0/config/tasks.json
Because
- A title in OpenAI connector JSON schema was missing.
This commit
- Adds missing title.
> chore(openai): add missing title

- go.mod
- go.sum
- pkg/base/component.go
- pkg/base/connector.go
- pkg/base/operator.go
- pkg/base/testdata/connectorDef.json
- pkg/base/testdata/wantConnectorDefinition.json
- pkg/connector/airbyte/v0/config/definition.json
- pkg/connector/archetypeai/v0/config/definition.json
- pkg/connector/bigquery/v0/config/definition.json
- pkg/connector/googlecloudstorage/v0/config/definition.json
- pkg/connector/googlesearch/v0/config/definition.json
- pkg/connector/huggingface/v0/config/definition.json
- pkg/connector/instill/v0/config/definition.json
- pkg/connector/numbers/v0/config/definition.json
- pkg/connector/openai/v0/config/definition.json
- pkg/connector/pinecone/v0/config/definition.json
- pkg/connector/redis/v0/config/definition.json
- pkg/connector/restapi/v0/config/definition.json
- pkg/connector/stabilityai/v0/config/definition.json
- pkg/connector/website/v0/config/definition.json
Because
- We've retired connector resource and merge its configuration into component configuration.
- We'd like to expose the `RenderJSON()` function for further usage.
This commit
- Renames `resource_specification` to `connection_specification`.
- Expose `RenderJSON()` function
> refactor: expose `RenderJSON()` and rename `resource_specification`

- pkg/connector/numbers/v0/main.go
Because
- The Numbers connector has a bug in the recipe data.
This commit
- Fixes the recipe data bug.
> fix(numbers): fix recipe data bug

- pkg/base/connector.go
- pkg/base/operator.go
- pkg/connector/instill/v0/README.mdx
- pkg/connector/instill/v0/config/definition.json
- pkg/connector/website/v0/README.mdx
- pkg/connector/website/v0/config/definition.json
- tools/compogen/pkg/gen/definition_test.go
- tools/compogen/pkg/gen/resources/templates/readme.mdx.tmpl
- tools/compogen/pkg/gen/schema.go
- tools/compogen/pkg/gen/schema_test.go
Because
- We want to avoid empty objects in our definitions if possible.
- New **Connection** section is empty for some connectors.
This commit
- **chore: reintroduce nonempty object validation**
- **fix: remove connection section if empty**
> chore: reintroduce nonempty object validation

- .github/CONTRIBUTING.md
- pkg/base/testdata/connectorDef.json
- pkg/base/testdata/wantConnectorDefinition.json
- pkg/connector/archetypeai/v0/config/definition.json
- pkg/connector/bigquery/v0/config/definition.json
- pkg/connector/googlecloudstorage/v0/config/definition.json
- pkg/connector/googlesearch/v0/config/definition.json
- pkg/connector/huggingface/v0/config/definition.json
- pkg/connector/numbers/v0/config/definition.json
- pkg/connector/openai/v0/config/definition.json
- pkg/connector/pinecone/v0/config/definition.json
- pkg/connector/redis/v0/config/definition.json
- pkg/connector/restapi/v0/config/definition.json
- pkg/connector/stabilityai/v0/config/definition.json
- tools/compogen/cmd/testdata/readme-connector.txt
Because
- We've retired the connector "resource" and made it a "connection" field in the component spec.
This commit
- Updates the title for the connection spec.
> chore: update title for connection spec

- .github/CONTRIBUTING.md
Because
- (write the reason why we need to consider this PR in a list)
This commit
- (write the summary of all commits in this PR in a list)
> fix: typos in contribution guide

- .github/CONTRIBUTING.md
Because
- there are typos found in `CONTRIBUTING.md`
This commit
- fix typos
> docs(contributing): fix typos

- pkg/base/execution.go
- pkg/connector/main.go
- pkg/connector/openai/v0/main.go
Because
- We need connectors like OpenAI to use globally configured secrets to run executions without credentials.
This commit
- Injects a global secret for the OpenAI API key on intialization.
- Transforms a keyword value in that configuration parameter into the secret.
> feat: allow global API key on OpenAI connector

- pkg/connector/pinecone/v0/main.go
Because
- pinecone needs to track the activities
This commit
- add instillai to SourceTag
> feat: add sourceTag for pinecone

- pkg/base/connector.go
- pkg/base/testdata/connectorDef.json
- pkg/base/testdata/wantConnectorDefinition.json
- pkg/connector/archetypeai/v0/config/definition.json
- pkg/connector/bigquery/v0/config/definition.json
- pkg/connector/googlecloudstorage/v0/config/definition.json
- pkg/connector/googlesearch/v0/config/definition.json
- pkg/connector/huggingface/v0/config/definition.json
- pkg/connector/main.go
- pkg/connector/numbers/v0/config/definition.json
- pkg/connector/openai/v0/config/definition.json
- pkg/connector/openai/v0/config/tasks.json
- pkg/connector/pinecone/v0/config/definition.json
- pkg/connector/redis/v0/config/definition.json
- pkg/connector/restapi/v0/config/definition.json
- pkg/connector/stabilityai/v0/config/definition.json
Because
- We need to introduce new attributes in the JSON schema to help Console generate the corresponding Instill-Credit-supported models list.
This commit
- refactor: rename `instillCredentialField` to `instillSecret`
- feat(openai): add additional attribute in JSON schema to indicate which models support `instillSecret`
- feat: update `instillEditOnNodeFields` for all connectors
> feat: add additional attribute in JSON schema for Instill Credit

- pkg/connector/openai/v0/config/tasks.json
Because
- We need to adjust Instill Credit supported model list.
This commit
- Updates the list.
> chore(openai): update Instill Credit supported model list

- pkg/base/connector.go
- pkg/base/operator.go
- pkg/base/usage.go
- pkg/connector/openai/v0/connector_test.go
- pkg/connector/openai/v0/main.go
- pkg/connector/openai/v0/text_generation.go
Because
- Usage handlers need to parse the input and output structures to collect e.g. token usage.
This commit
- Expose required structs and constants as exported.
> chore: make input / output OpenAI fields public

- pkg/base/connector.go
- pkg/connector/main.go
- pkg/connector/openai/v0/main.go
- pkg/connector/stabilityai/v0/client.go
- pkg/connector/stabilityai/v0/connector_test.go
- pkg/connector/stabilityai/v0/main.go
Because
- We want to support global secrets on StabilityAI
This commit
- Adds global secrets and usage handler on StabilityAI
> feat: add global secrets to StabilityAI connector

- pkg/connector/openai/v0/config/tasks.json
- pkg/connector/stabilityai/v0/config/definition.json
- pkg/connector/stabilityai/v0/config/tasks.json
Because
- We'll support Instill Secrets for OpenAI test_embedding and StabilityAI text_to_image.
This commit
- Updates Instill Secrets supported model list.
> feat: update Instill Credit supported model list

- pkg/base/execution.go
- pkg/base/usage.go
- pkg/connector/openai/v0/connector_test.go
Because
- Some errors when creating a usage handler come from validating the execution.
We don't need to wait for the `Check` / `Collect` methods in order to detect
them.
This commit
- Adds an error to the `UsageHandlerCreator` interface
> chore: add error to UsageHandlerCreator interface

- pkg/connector/openai/v0/config/openai.json
- pkg/connector/openai/v0/config/tasks.json
Because
- OpenAI has released new gpt-4o model.
This commit
- Adds gpt-4o and gpt-4-turbo model into model list.
> feat(openai): support gpt-4o model

- pkg/connector/openai/v0/audio_transcriptions.go
- pkg/connector/openai/v0/main.go
Because
- Credit collection for speech recognition requires input audio duration.
This commit
- Calls OpenAI's speech recognition with the [`verbose_json`](https://github.com/openai/openai-openapi/blob/master/openapi.yaml#L8942) flag and sets the duration in the output.
- Duration isn't part of the schema, so the executor's usage handler can read it but it won't be part of the UI.
> chore: extract duration from speech recognition

- pkg/connector/instill/v0/main.go
- pkg/connector/restapi/v0/main.go
Because
- We can skip the dynamic component definition generation if the params are empty. 
This commit
- Optimizes `GetConnectorDefinition()` for the rest and Instill connector.
> chore: optimize GetConnectorDefinition

- .github/labeler.yml
Because
- Instill Component is now a new product category to delimit Instill VDP
This commit
- change PR auto-label
> ci(github): change PR auto-label to instill component

- pkg/connector/pinecone/v0/README.mdx
- pkg/connector/pinecone/v0/config/definition.json
- pkg/connector/slack/v0/README.mdx
- pkg/connector/slack/v0/config/definition.json
Because
- Slack token document is unclear for users
This commit
- Add the instruction.
- Note: please check the reference in [Linear](https://linear.app/instill-ai/issue/INS-4686/improve-slack-document#comment-85d32dd7)
> chore: update document to lead the users to get Slack token

- store/store.go
Because
- We should rename `connector` to `component`.
This commit
- Fixes typo in store.go.
> chore: fix typo in store.go

- .github/CONTRIBUTING.md
Because
- We need to document all the JSON properties in the component definition.
This commit
- Updates contribution guideline.
- Rewraps the content.
> docs(contribution): update contribution guideline

- Makefile
Because
- local unit testing is essential while running `go test ./...` currently requires a `-tag ocr` due to the [docconv](https://github.com/sajari/docconv) package using [tesseract](https://tesseract-ocr.github.io)
This commit
- add `make test`
> ci(Makefile): add test target

- operator/document/v0/config/definition.json
Because
- The `type` in definition is missing.
This commit
- Adds missing `type` in definition.
> chore(document): add missing `type` in definition

- operator/document/v0/convert_pdf_to_markdown.go
Because
- the stdin in a thread is not closed, so the pipeline stuck.
This commit
- fix the sequence of close of stdin
> fix: bug of failure of document component

- operator/document/v0/config/tasks.json
- operator/document/v0/convert_pdf_to_markdown.go
- operator/document/v0/convert_pdf_to_markdown_test.go
- operator/document/v0/python/transformPDFToMarkdown.py
Because
- AI engineers want to exclude the image tag when they do not want to include them.
This commit
- Add toggle option in pdf to markdown task in document operator
> feat: add toggle image tag function for document pdf to markdown task

- .github/CONTRIBUTING.md
Because
- id is required to be with hyphen
This commit
- modify the document to align the rule.
> chore: change underscore to hyphen for component id

- ai/stabilityai/v0/config/stabilityai.json
Because
- The default value of width and height is 512. But it will cause error since most of the model don't accept it.
This commit
- Adjusts default value for image-height/width to 1024.
> chore(stabilityai): adjust default value for image-height/width

- ai/instill/v0/image_classification.go
- ai/instill/v0/instance_segmentation.go
- ai/instill/v0/keypoint_detection.go
- ai/instill/v0/main.go
- ai/instill/v0/object_detection.go
- ai/instill/v0/ocr.go
- ai/instill/v0/semantic_segmentation.go
Because
- The unmarshalling in the Instill component is incorrect due to the recent refactor involving camelCase and kebab-case.
This commit
- Fixes the incorrect unmarshalling in the Instill component.
Note:
- We'll soon refactor the Instill Model component data format to align it with the data format in Instill Model, ensuring no differences in the future.
> chore(instill): fix incorrect unmarshalling in Instill component

- data/redis/v0/config/definition.json
- data/redis/v0/config/tasks.json
Because
- The task enum is wrong.
This commit
- Fixes the typo
> fix(redis): fix typo

- ai/openai/v0/text_generation.go
Because
- The `image_url` field in OpenAI component was not working due to a typo.
This commit
- Fixes the `image_url` field in OpenAI component.
> fix(openai): fix OpenAI image_url field can't work

- data/googlecloudstorage/v0/README.mdx
- data/googlecloudstorage/v0/config/definition.json
- data/googlecloudstorage/v0/config/setup.json
- data/googlecloudstorage/v0/config/tasks.json
- data/googlecloudstorage/v0/create_bucket.go
- data/googlecloudstorage/v0/main.go
- data/googlecloudstorage/v0/main_test.go
- data/googlecloudstorage/v0/read_objects.go
Because
- we do not have read objects and create bucket task for gcs
This commit
- add read task for gcs
- add create bucket task for gcs
> feat: add read task for gcs

- ai/anthropic/v0/README.mdx
- ai/anthropic/v0/config/tasks.json
- ai/instill/v0/README.mdx
- ai/instill/v0/config/tasks.json
- ai/instill/v0/image_to_image.go
- ai/instill/v0/llm_utils.go
Because
- The `extra-params` field in the Instill Model component is confusing and difficult for users to understand. To improve usability, we have decided to remove it.
This commit
- Removes `extra-params` field.
> feat(instill): remove extra-params field

- ai/anthropic/v0/component_test.go
- ai/anthropic/v0/main.go
Because
- calculator should rely on component package
This commit
- expose the input and output for the package
> fix: expose input and output for anthropic for instill credit

- ai/anthropic/v0/component_test.go
- ai/anthropic/v0/main.go
- ai/archetypeai/v0/component_test.go
- ai/archetypeai/v0/main.go
- ai/huggingface/v0/component_test.go
- ai/huggingface/v0/main.go
- ai/openai/v0/component_test.go
- ai/openai/v0/main.go
- ai/stabilityai/v0/component_test.go
- ai/stabilityai/v0/main.go
- application/restapi/v0/component_test.go
- application/slack/v0/component_test.go
- base/component.go
- base/component_test.go
- base/execution.go
- base/execution_test.go
- base/usage.go
- data/pinecone/v0/component_test.go
- operator/json/v0/component_test.go
- operator/text/v0/main_test.go
- store/store.go
Because
- We have usage handlers for pipeline and component but the former only receives the number of components. We can merge them and simplify our logic.
- When a component is configured to use (secret) credentials injected from the environment variables in the configuration (e.g. when a global OpenAI API key is set), the component logic always references these values as global secrets, and sometimes just "secrets". This is confusing because users can define their own secrets. "Instill Credentials" is more concrete and less confusing.
- The `GetID()` method in the `IComponent` interface actually refers to the component definition ID. At some point we'll actually want to know the component ID (i.e. the component in the pipeline `mycomponent-1` vs the definition `mycomponent`), e.g. for …
> feat: unify pipeline and component usage handlers

- ai/openai/v0/config/tasks.json
- ai/openai/v0/main.go
- ai/openai/v0/text_embeddings.go
Because
- in many use cases, users may not need to output vectors of such high dimensionality and might only require the first 'x' dimensions.
This commit
- add dimensions in api caller
> feat(openai): add dimensions in openai component

- ai/instill/v0/main.go
Because
- Instill Model will [use the requester UID,](https://github.com/instill-ai/model-backend/pull/619/files) when present, in model execution.
This commit
- Adds the requester header to the trigger model call in the `instill` component.
> feat(instill): send requester UID, if present, on model trigger

- application/github/v0/README.mdx
- application/github/v0/config/tasks.json
- application/github/v0/issues.go
- application/github/v0/pull_request.go
- application/github/v0/review_comment.go
- application/github/v0/utils.go
Because
- Users may want to control how much data they wish to receive.
This commit
- Add pagination options to all list tasks
- Update readme
> feat: GitHub component pagination

- ai/cohere/v0/component_test.go
- ai/cohere/v0/config/tasks.json
- ai/cohere/v0/embedding.go
- ai/cohere/v0/main.go
- ai/cohere/v0/rerank.go
- ai/cohere/v0/text_generation.go
- store/store.go
Because
- we should expose users' input & output for instill credit calculation
- The logic between cloud & local should align
This commit
- expose users' input & output
- refactor the embedding function to make the business logic function exposed
> feat(cohere): add cohere to be able to use instill credit

- operator/json/v0/README.mdx
- operator/json/v0/component_test.go
- operator/json/v0/config/tasks.json
- operator/json/v0/main.go
Because
- The `jq` task took only strings, which can be leveraged for reference but forced users to pre-process objects with another JSON operator that marshalled the input.
This commit
- Introduces a new input field for the task, which can be any object
- The old value is hidden under the "More" settings section. If the new field is empty, task will fall back to the old field (for backwards compatibility).
- Removes object type assumption in unmarshal task: now it can unmarshal any valid JSON value.
> feat: add JQ input field that accepts any type

- ai/mistralai/v0/component_test.go
- ai/mistralai/v0/tasks.go
Because
- We need the task input and output struct in the usage handler.
This commit
- Exposes the task input and output struct.
> chore(mistralai): expose input and output struct

- store/store.go
Because
- We don't allow hyphens in the component ID when initiating the Instill Credential.
This commit
- Fixes the import ID for Instill Credential.
> chore(mistral): fix the import ID for Instill Credential

- base/component.go
Because
- The instillUpstreamTypes do not correctly render the JSON schema when it is under `anyOf`, `oneOf`, or `allOf`.
This commit
- Fixes the bug.
> fix: fix instillUpstreamTypes not correctly render the JSON schema

- operator/json/v0/README.mdx
- operator/json/v0/component_test.go
- operator/json/v0/config/tasks.json
- operator/json/v0/main.go
- tools/compogen/cmd/root.go
- tools/compogen/cmd/testdata/readme-operator.txt
- tools/compogen/cmd/testdata/usage.txt
- tools/compogen/pkg/gen/readme.go
- tools/compogen/pkg/gen/schema.go
Because
- Migration to `kebab-case` didn't include JQ task in JSON operator.
This commit
- Updates JQ input fields with `kebab-case` names.
- Updates `compogen` to ignore deprecated fields.
> chore: use kebab-case in JSON operator

- .github/CONTRIBUTING.md
Because
- In order to have better end-user errors, contributors must know about the mechanism to bubble up errors with attached messages.
This commit
- Adds a mention to [`errmsg`](https://github.com/instill-ai/x/tree/main/errmsg) in the contribution guidelines.
> chore: explain end-user messages in contribuiton guidelines

- operator/text/v0/chunk_text.go
- operator/text/v0/chunk_text_test.go
- operator/text/v0/markdown_splitter.go
Because
- there is out of the range of the slice when the chunks are in some conditions
- the markdown chunking is not controllable in LangChainGo
This commit
- Rescan the raw text to make the chunk scanning will not be out of the slice
- Replace markdown chunking with custom logic that required for RAG system
Please check Markdown Chunking Logic Document in Linear as reference.
> fix(text): fix bug and replace markdown chunking

- operator/json/v0/.compogen/extra-jq.mdx
- operator/json/v0/README.mdx
- operator/json/v0/component_test.go
- operator/json/v0/config/definition.json
- operator/json/v0/config/tasks.json
- operator/json/v0/main.go
Because
- JSON operator documentation could be clearer.
This commit
- Replaces "JSON object" by "JSON entity" in order to reflect that any JSON datatype is accepted. Technically "object" is valid but it might be confused with the JSON hash type.
- Adds an extra section to document `jq` and share some examples.
> chore: improve JSON operator documentation

- operator/text/v0/chunk_text.go
- operator/text/v0/markdown_splitter.go
Because
- we miss to append the final document
- If there is no chunk in split, we make all document as a chunk.
- The definition missed a case for hashtag in header
This commit
- fix the bug to append the final document into the documents
- fix the bug that did not count a chunk as 1
- add the definition in hashtag in header
> fix: fix markdown chunking bugs

- application/github/v0/config/tasks.json
Because
- Some fields miss "instillAcceptFormats" and "instillUpstreamFormats", and cause the frontend hint to be missing.
This commit
- Patch these fields
> fix(github): patch missing fields

- application/restapi/v0/main.go
Because
- `restapi` component would miss the response body if it is not a JSON
This commit
- check whether the body is nil, if true, assign the response as a string
- maintain body in JSON structure to avoid frontend render overhead
- as the frontend would split the plain text into thousands of div if the body is large
> fix(restapi): fix response body missing problem

- application/github/v0/main.go
- base/component.go
Because:
- Request from frontend and direct API calls may miss some optional fields
- The underlying meaning of default is that if no value is provided, we will use this value instead.
This commit
- Implement a function in the `base` package for all components to use
- The function supports filling fields with primitive types, including string, integer, number, boolean, and array of them.
- Support allOf, anyOf, oneOf fields
- Recursively fill in multi-layer object value
> feat: add handler to auto-fill missing default values

- application/github/v0/main.go
- application/slack/v0/main.go
- base/component.go
- go.mod
- go.sum
- store/store.go
Because
- We are introducing the run-on-event feature, which allows users to configure webhook event handlers for each vendor.
This commit
- Introduces an event handler interface to: 
1. Handle verification/ping events.
2. Handle data events.
Note
- This is still an experimental feature and may change at any time.
> feat: introduce event handler interface

- ai/instill/v0/main.go
Because
- We don't need `VIEW_FULL` for retrieving the entire model definition.
This commit
- Uses `VIEW_BASIC` when sending requests to Instill Model.
> chore(instill): use VIEW_BASIC when sending request to Instill Model

- operator/text/v0/markdown_splitter.go
- operator/text/v0/markdown_splitter_test.go
Because
- we have the duplicate document in the logic, which is the bug
This commit
- fix the bug with not executing the same code within and out the loop
- add the test code to test markdown chunking logic specifically
> fix: bug of duplicate document

- operator/audio/v0/config/tasks.json
- operator/video/v0/config/tasks.json
- operator/video/v0/video_operation.go
Because
- The codec wasn't displaying correctly on Console.
This commit
- Fixes the video codec by setting the MIME header to mp4 and the format to `yuv420p`, making it viewable on most players.
> chore(video): fix video codec

- ai/instill/v0/client.go
Because
- Instill Model component didn't send correct request.
This commit
- Fixes trigger bug
> chore(instill): fix trigger bug

- application/googlesearch/v0/README.mdx
- application/googlesearch/v0/config/setup.json
Because
- there is typo in doc
This commit
- fix the typo
> chore(googlesearch): fix syntax

- operator/document/v0/python/transformPDFToMarkdown.py
Because
- we want to support English when transform pdf to markdown
- we do not support bold in the current version
This commit
- remove loop to insert character but a line
> fix: ignore bold case and add all line to result

- ai/ollama/v0/.compogen/setup-hosting.mdx
- ai/ollama/v0/README.mdx
- ai/ollama/v0/main.go
Because
- We want to help users setup ollama instance and connect it to VDP.
This commit
- Add documentation with:
- Install ollama
- Expose ollama to local network
- Connect ollama server to ollama client on VDP
> chore(ollama): add documentation to self hosting ollama instance

- operator/document/v0/README.mdx
- operator/document/v0/config/tasks.json
- operator/document/v0/convert_document_to_markdown.go
- operator/document/v0/convert_document_to_markdown_test.go
- operator/document/v0/markdown_transformer.go
Because
- The original PDF-to-Markdown algorithm is not robust.
This commit
- Integrates `pdf2md` into the document operator.
> feat(document): integrate pdf2md in document operator

- application/numbers/v0/main.go
- store/store.go
Because
- Numbers Protocol has introduced a new header `x-api-key` for identification.
This commit
- Supports `x-api-key` header.
> chore(numbers): support x-api-key header

- data/artifact/v0/config/tasks.json
Because
- the file name should include file extension as suffix
This commit
- add description for users
> fix(artifact): add the description to remind users to add file extension

- ai/fireworksai/v0/config/tasks.json
- ai/groq/v0/config/tasks.json
Because
- the pricing info is not clear yet
This commit
- take out models that cannot support by instill credit now
> feat(groq, fireworksai): take out the unsupported models from instill credit

- go.mod
- go.sum
- internal/util/helper.go
- operator/document/v0/README.mdx
- operator/document/v0/config/definition.json
- operator/document/v0/config/tasks.json
- operator/document/v0/convert.go
- operator/document/v0/convert_document_to_markdown.go
- operator/document/v0/convert_test.go
- operator/document/v0/convert_to_images.go
- operator/document/v0/main.go
- operator/document/v0/markdown_transformer.go
Because
- For ins-5826
- we want the filename can be passed to the artifact component or other components in the future
- For ins-5821
- we want to convert PDF to images
- For ins-5823
- we want to convert xlsx to markdown
This commit
- For ins-5826
- add filename (optional) for the input of
- Convert To Markdown
- Convert To Text
- add filename for the output of Convert To Markdown
- <name>.md if the input.filename is set
- add filename for the output of Convert To Text
- <name>.txt if the input.filename is set
- For ins-5821
- It converts pdf to images with filenames
- For ins-5823
- It converts xlsx to markdown to several tables for sheets
- other
-  take out jpg to text from Convert to text because of unknown bug
> feat(document): improve document operator

- operator/document/v0/markdown_transformer.go
Because
- we cannot read pivot table with the current package
This commit
- catch the error if there is no data in sheet
> fix(document): catch the error if there is no data in sheet

- store/store.go
Because
- Clients (i.e. `pipeline-backend`) need to discern not found errors from other
errors when fetching a component definition.
This commit
- Returns an error type instead of just a message so clients can perform a check
to detect the not found scenario.
> feat: use error type for component definition not found error

- base/execution_wrapper.go
- base/execution_wrapper_test.go
Because
- We can encapsulate the usage handler and data validator within `InputReader` and `OutputWriter`.
This commit 
- Refactors the code.
> refactor: encapsulate operations in InputReader and OutputWriter

- operator/document/v0/convert.go
- operator/document/v0/convert_document_to_markdown.go
- operator/document/v0/convert_document_to_markdown_test.go
- operator/document/v0/convert_to_images.go
- operator/document/v0/main.go
- operator/document/v0/markdown_transformer.go
Because
- We need to directly use certain functions from the document operator in the pipeline-backend.
This commit
- Exports the necessary operator functions.
> refactor(document): export operator functions

- ai/anthropic/v0/README.mdx
- ai/anthropic/v0/component_test.go
- ai/anthropic/v0/config/setup.json
- ai/anthropic/v0/main.go
- ai/cohere/v0/README.mdx
- ai/cohere/v0/component_test.go
- ai/cohere/v0/config/setup.json
- ai/cohere/v0/main.go
- ai/fireworksai/v0/README.mdx
- ai/fireworksai/v0/component_test.go
- ai/fireworksai/v0/config/setup.json
- ai/fireworksai/v0/main.go
- ai/groq/v0/README.mdx
- ai/groq/v0/component_test.go
- ai/groq/v0/config/setup.json
- ai/groq/v0/main.go
- ai/mistralai/v0/README.mdx
- ai/mistralai/v0/component_test.go
- ai/mistralai/v0/config/setup.json
- ai/mistralai/v0/main.go
- ai/openai/v0/README.mdx
- ai/openai/v0/component_test.go
- ai/openai/v0/config/setup.json
- ai/openai/v0/main.go
- ai/stabilityai/v0/README.mdx
- ai/stabilityai/v0/component_test.go
- ai/stabilityai/v0/config/setup.json
- ai/stabilityai/v0/main.go
Because
- In the new low-code editor, users need to type the recipe manually. Asking users to write `${secret.INSTILL_SECRET}` is not user-friendly. We decided to make these fields optional; if the key is empty, the component will use built-in keys.
This commit
- Makes the API key optional for Instill-Credit-supported components.
> feat: make the API key be optional for Instill-Credit-supported component

- operator/text/v0/chunk_text.go
- operator/text/v0/chunk_text_test.go
Because
- there will be a bug when there are 2 exact same chunks in a row
This commit
- make sure the position is strictly increased
> fix(text): fix the bug if there are 2 exact same chunks

- ai/openai/v0/main.go
- base/execution_wrapper.go
- base/execution_wrapper_test.go
Because
- Previously, the OpenAI component sent requests to the OpenAI service sequentially.
This commit
- Sends requests to OpenAI in parallel to improve the performance.
Note
- We have skipped output validation for now because the streaming feature is not compatible with the validator.
> refactor(openai): send requests to OpenAI in parallel

- operator/document/v0/README.mdx
- operator/document/v0/config/tasks.json
- operator/document/v0/convert_document_to_markdown.go
- operator/document/v0/convert_document_to_markdown_test.go
- operator/document/v0/main.go
- operator/document/v0/markdown_transformer.go
- operator/document/v0/pdf_to_markdown_converter.go
- operator/document/v0/python/transformPDFToMarkdown.py
Because
- we do not extract images from PDF
- we do not recognise tables & LaTex in current converter
This commit
- improve pdfplumber and extract image base64
> feat(document): improve convert to markdown

- operator/text/v0/markdown_document.go
- operator/text/v0/markdown_splitter.go
Because
- It missed a case of parsing the markdown
This commit
- add the missing case
> fix(text): markdown chunking bug

- ai/openai/v0/main.go
Because
- Occasional unexpected EOF errors from OpenAI.
This commit
- Adds a retry mechanism for OpenAI requests.
> chore(openai): add retry for OpenAI request

- operator/document/v0/convert.go
- operator/document/v0/convert_test.go
Because
- there is a bug when using docconv when converting jpg
This commit
- fix the bug with jpg -> png -> text
> fix(document): fix jpg conversion bug

- operator/web/v0/crawl_website.go
- operator/web/v0/main.go
- operator/web/v0/scrape_webpage.go
Because
- bug about no domain url in the links
- bug about slow response of crawler
This commit
- fix bug by adding domain to non-domain link
- improve by requesting static html data if the context is canceled.
- improve by requesting in parallel
> fix(web): fix bugs related to web operator

- data/instillartifact/v0/artifact_operation.go
- data/instillartifact/v0/main_test.go
Because
- we did not fetch next page tokens when the file count is more than a page
- the previous upload file design is not good because it catches the error by error message, which is not robust
This commit
- fetch next page tokens
- list all catalogs first and create a new one if there isn't existing
> fix(instillartifact): fix bugs

- store/store.go
Because
- we will release instill app and universal ai on sprint 45
This commit
- take out the store init
> chore: take out instill app and universal ai component for sprint 44 release

- ai/universalai/v0/README.mdx
- generic/collection/v0/README.mdx
- generic/collection/v0/config/definition.json
- generic/collection/v0/config/tasks.json
- generic/collection/v0/main.go
- go.mod
- go.sum
Because
- We want to provide set operations.
This commit
- Introduces new set operations: `TASK_UNION`, `TASK_INTERSECTION`, and `TASK_DIFFERENCE`.
> feat(collection): introduce TASK_UNION, TASK_INTERSECTION and TASK_DIFFERENCE

- generic/collection/v0/README.mdx
- generic/collection/v0/config/definition.json
- generic/collection/v0/config/tasks.json
- generic/collection/v0/main.go
Because
- The Append operation always applies to an array, so there’s no need to name it as `TASK_APPEND_ARRAY`.
This commit
- Renames `TASK_APPEND_ARRAY` to `TASK_APPEND`.
> chore(collection): rename TASK_APPEND_ARRAY to TASK_APPEND

- operator/text/v0/markdown_document.go
Because
- there is a bug when targeting table
This commit
- fix the bug about table judgement
> fix(text): bug about table judgement in markdown chunking

- data/elasticsearch/v0/README.mdx
- data/elasticsearch/v0/config/tasks.json
Because
- there is a typo
This commit
- fix typo
> chore(elasticsearch): fix typo

- ai/openai/v0/main.go
Because
- We used concurrent API calls for the OpenAI TaskEmbedding. But actually, OpenAI provide the batch inference for embedding.
This commit
- Uses the batch inference provided by OpenAI.
> feat(openai): use batch inference for embedding

- base/formats.go
Because
- The InstillAcceptFormats validator
This commit
- Adds nil check in InstillAcceptFormats validator
> chore: add nil check in InstillAcceptFormats validator

- base/formats.go
Because
- The input validator can not validate array format.
This commit
- Fixes the bug.
> fix: the input validator can not validate array format

- go.mod
- operator/web/v0/README.mdx
- operator/web/v0/config/tasks.json
- operator/web/v0/crawl_website.go
Because
- async process should lock first before inserting data to avoid race condition
- colly can parse response onResponse
This commit
- fix the bug
- refactor the web crawl, and it will improve the speeds and save the resources
> fix(web): fix bugs and improve the performance
